# Generated by Django 3.0.5 on 2020-04-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=20)),
                ('sub_category', models.CharField(max_length=40)),
                ('search_word', models.CharField(max_length=200)),
                ('article', models.TextField()),
            ],
            options={
                'db_table': 'Knowledge',
            },
        ),
    ]
